Enhance CI with SonarQube Quality Gate and notifications
Added SonarQube Quality Gate Check and email notifications for scan results.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -5,7 +5,6 @@ on:
     branches:
       - master
 
-
 jobs:
   build:
     name: Build and analyze
@@ -14,14 +13,46 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-      - uses: SonarSource/sonarqube-scan-action@v6
+          fetch-depth: 0
+
+      - name: SonarQube Scan
+        uses: SonarSource/sonarqube-scan-action@v6
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-      # If you wish to fail your job when the Quality Gate is red, uncomment the
-      # following lines. This would typically be used to fail a deployment.
-      # - uses: SonarSource/sonarqube-quality-gate-action@v1
-      #   timeout-minutes: 5
-      #   env:
-      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+      - name: SonarQube Quality Gate Check
+        id: sonarqube-quality-gate-check
+        uses: SonarSource/sonarqube-quality-gate-action@v1
+        timeout-minutes: 5
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+      - name: Fail pipeline if Quality Gate fails
+        if: steps.sonarqube-quality-gate-check.outputs.quality-gate-status == 'FAILED'
+        run: |
+          echo "Quality Gate failed due to vulnerabilities"
+          exit 1
+
+      - name: Send email on SUCCESS (No Vulnerabilities)
+        if: steps.sonarqube-quality-gate-check.outputs.quality-gate-status == 'PASSED'
+        uses: hilarion5/send-mail@v1
+        with:
+          smtp-server: smtp.gmail.com
+          smtp-port: 587
+          smtp-secure: false
+          username: ${{ secrets.EMAIL_USERNAME }}
+          password: ${{ secrets.EMAIL_PASSWORD }}
+          from-email: ${{ secrets.EMAIL_USERNAME }}
+          to-email: lijazsalim@gmail.com,asadchamp109@gmail.com
+          subject: "SUCCESS: SonarQube Scan Passed"
+          html: |
+            <h2 style="color:green;">Pipeline Successful</h2>
+            <p>No vulnerabilities found in SonarQube scan.</p>
+
+            <p><b>Repository:</b> ${{ github.repository }}</p>
+            <p><b>Branch:</b> ${{ github.ref_name }}</p>
+
+            <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">
+              View Pipeline Report
+            </a>
